export const LOG4JS_PROVIDER = 'LOG4JS_PROVIDER';
export const LOG4JS_CONFIG = 'LOG4JS_CONFIG';
export const LOG4JS_REQUEST_LOGGER = 'LOG4JS_REQUEST_LOGGER';
export const LOG4JS_RESPONSE_LOGGER = 'LOG4JS_RESPONSE_LOGGER';
export const LOG4JS_ERROR_LOGGER = 'LOG4JS_ERROR_LOGGER';